example-publish-frontend:
  image: $ALPINE_IMAGE
  stage: deploy
  when: manual
  needs:
    - job: build-docker-frontend
      artifacts: true
  script:
    - echo "i should publish an docker image"

example-publish-backend:
  image: $ALPINE_IMAGE
  stage: deploy
  when: manual
  needs:
    - job: build-docker-api
      artifacts: true
  script:
    - echo "i should publish an docker image"


deploy-api:
  image: $ALPINE_IMAGE
  stage: deploy
  when: manual
  needs:
    - job: build-docker-api
      artifacts: true
  script:
    - echo "test deploy"

deploy-ui:
  image: $ALPINE_IMAGE
  stage: deploy
  when: manual
  needs:
    - job: build-docker-frontend
      artifacts: true
  script:
    - echo "test deploy"